export const LAND_PERCENT = 0.2
export const BUILDING_DEPRECIATION_RATE = 0.025
export const FURNITURE_DEPRECIATION_RATE = 0.1
export const BAILLEUR_PRIVE_BUILDING_RATE = 0.03
export const BAILLEUR_PRIVE_TAX_CAP_EUR = 8000
